# Generated by Django 5.2.1 on 2025-05-31 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('wikipedia', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('capa', models.ImageField(upload_to='capa_filmes')),
                ('sinopse', models.TextField()),
                ('elenco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ator')),
            ],
        ),
    ]
