# Generated by Django 5.2.1 on 2025-05-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='elenco',
        ),
        migrations.AddField(
            model_name='filme',
            name='elenco',
            field=models.ManyToManyField(to='main.ator'),
        ),
    ]
