# Generated by Django 5.2.1 on 2025-05-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='direcao',
            field=models.ManyToManyField(blank=True, related_name='direcao', to='main.pessoa'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='elenco',
            field=models.ManyToManyField(blank=True, related_name='elenco', to='main.pessoa'),
        ),
    ]
