# Generated by Django 5.2.1 on 2025-05-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_filme_direcao_alter_filme_elenco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto'),
        ),
    ]
