# Generated by Django 5.2.1 on 2025-06-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pessoa_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ator',
        ),
        migrations.DeleteModel(
            name='Diretor',
        ),
    ]
