# Generated by Django 5.2.1 on 2025-06-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_aluguel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='data_aluguel',
            field=models.DateField(auto_now_add=True, default='20070912'),
            preserve_default=False,
        ),
    ]
