# Generated by Django 5.2.1 on 2025-06-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_aluguel_data_aluguel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='duracao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='direcao',
            field=models.ManyToManyField(related_name='filmes_dirigidos', to='main.pessoa'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='elenco',
            field=models.ManyToManyField(related_name='filmes_atuados', to='main.pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(upload_to='foto'),
        ),
    ]
