# Generated by Django 5.2.1 on 2025-07-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_filme_duracao_alter_filme_direcao_alter_filme_elenco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
