# Generated by Django 5.2.1 on 2025-07-27 20:00

from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Filmes = apps.get_model('main', 'Filme')
    for filme in Filmes.objects.all():
        filme.slug = f"{slugify(filme.titulo)}"
        filme.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_filme_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs)
    ]
