# Generated by Django 5.2.1 on 2025-07-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20250727_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='slug',
            field=models.CharField(max_length=150),
        ),
    ]
