# Generated by Django 5.2.1 on 2025-07-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_filme_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
