# Generated by Django 5.2.1 on 2025-07-27 20:10

from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Genero = apps.get_model('main', 'Genero')
    for genero in Genero.objects.all():
        genero.slug = f"{slugify(genero.nome)}"
        genero.save()

    Pessoa = apps.get_model('main', 'Pessoa')
    for pessoa in Pessoa.objects.all():
        pessoa.slug = f"{slugify(pessoa.nome)}"
        pessoa.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_genero_slug_pessoa_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs)
    ]
