# Generated by Django 5.2.1 on 2025-07-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20250727_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='slug',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='slug',
            field=models.CharField(max_length=150),
        ),
    ]
