# Generated by Django 5.2.1 on 2025-07-28 13:30

import functools
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_genero_slug_alter_pessoa_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluguel',
            options={'verbose_name_plural': 'Alugueis'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Gênero'},
        ),
        migrations.AlterField(
            model_name='filme',
            name='capa',
            field=models.ImageField(upload_to=functools.partial(main.models.get_filename_generator, *('capa-filmes',), **{})),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(upload_to=functools.partial(main.models.get_filename_generator, *('foto',), **{})),
        ),
    ]
